#!/bin/bash

[ $# -ge 1 ] || { echo "Usage: $0 /path/to/bundle_dir"; exit 1; }
BUNDLE_DIR=$1
mkdir -p $BUNDLE_DIR
mkdir $BUNDLE_DIR/bin

FIRE_SCRIPT=${0//bundle/fire}
RR_PATH=$(which rr)
RR_LIBS=$(ldd $RR_PATH | grep "=>" | awk '{print $3}' | sort -u)
RR_LD=$(ldd $RR_PATH | grep ld-linux | awk '{print $1}')
RR_BIN_PATH=$(dirname $RR_PATH)
cp -L $RR_LIBS $RR_LD $BUNDLE_DIR
cp -L $RR_PATH $BUNDLE_DIR/bin/
cp -L $FIRE_SCRIPT $BUNDLE_DIR/fire