#!/bin/sh

ulimit -c unlimited
ulimit -f unlimited

OUR_DIR=$(dirname $0)
export PATH=$PATH:$OUR_DIR/bin/
export LD_LIBRARY_PATH=$OUR_DIR/libs
exec $OUR_DIR/ld-linux-* --library-path $OUR_DIR/libs $OUR_DIR/bin/gdb "$@"