#!/bin/bash

[ $# -ge 1 ] || { echo "Usage: $0 /path/to/bundle_dir"; exit 1; }
BUNDLE_DIR=$1
mkdir -p $BUNDLE_DIR

FIRE_SCRIPT=${0//bundle/fire}
STRACE_PATH=$(which strace)
STRACE_LIBS=$(ldd $STRACE_PATH | grep "=>" | awk '{print $3}' | sort -u)
STRACE_LD=$(ldd $STRACE_PATH | grep ld-linux | awk '{print $1}')
cp -L $STRACE_PATH $STRACE_LIBS $STRACE_LD $BUNDLE_DIR
cp -L $FIRE_SCRIPT $BUNDLE_DIR/fire
